### ISSUE TITLE
USA military reserved states

### ISSUE THREAD

**Issue by skoulix** [khkwan0/countryCityStateJson#10]
Thanks for your work. One question.
Is it possible to add some reserved states used for military personnel in USA?
E.g. AP, AE, AA
In case you are interested and want to read more => https://support.govx.com/hc/en-us/articles/226407608-Shipping-via-Military-Mail-APO-FPO-DPO-

**Comment by khkwan0** [comment]
Hi that is very possible. pretty.  Really easy to add it yourself.  There
are some directions in the readme.  How many entries are we talking about?

**Comment by skoulix** [comment]
Yes it's very easy to add. I think these are 3 entries in total.
Thanks for your reply.

**Comment by khkwan0** [comment]
I added those states to the USA (AA, AE, AP) and published a new npm package.  please check to see if they are in there.

**Comment by skoulix** [comment]
You are awesome. I really appreciate it. 
Thanks!
