### ISSUE TITLE
Need to update Australian Data

### ISSUE THREAD

**Issue by andrewjdavison** [khkwan0/countryCityStateJson#17]
Hi, There are Australian cities mixed in with the Australian State data. I've updated in the attached files.

Regards,

Andy
[new_city_state_files.zip](https://github.com/khkwan0/countryCityStateJson/files/9691364/new_city_state_files.zip)

**Comment by khkwan0** [comment]
Thanks i will i uodate asap

**Comment by khkwan0** [comment]
updated and released to npm a few days ago

**Comment by andrewjdavison** [comment]
Thanks – any thoughts about me going in and wholesale aligning the Australian data to the government source data? Like I said it’s a large number of entries, but will fix the inaccuracies that still exist.

Andy

From: Kenneth Kwan ***@***.***>
Date: Friday, 24 February 2023 at 3:15 pm
To: khkwan0/countryCityStateJson ***@***.***>
Cc: andrewjdavison ***@***.***>, Author ***@***.***>
Subject: Re: [khkwan0/countryCityStateJson] Need to update Australian Data (Issue #17)

Closed #17<https://github.com/khkwan0/countryCityStateJson/issues/17> as completed.

**Comment by khkwan0** [comment]
Would love to have the most accurate database as possible.  Seems to be a lot of work though.  Maybe we can do it a little at a time.

**Comment by andrewjdavison** [comment]
Easier to bite the bullet. I have extracted the data from a government source, and can write a short script to drop it into a JSON format and then incorporate it into the code. Will have a crack tonight and sub a PR for you to look at.

Andy

From: Kenneth Kwan ***@***.***>
Date: Friday, 24 February 2023 at 5:23 pm
To: khkwan0/countryCityStateJson ***@***.***>
Cc: andrewjdavison ***@***.***>, Author ***@***.***>
Subject: Re: [khkwan0/countryCityStateJson] Need to update Australian Data (Issue #17)

Would love to have the most accurate database as possible. Seems to be a lot of work though. Maybe we can do it a little at a time.
