### ISSUE TITLE
India States data is wrong . 

### ISSUE THREAD

**Issue by Saajan** [khkwan0/countryCityStateJson#3]

**Comment by khkwan0** [comment]
Yes, the databases I pulled from I noticed had some missing or wrong information.  But it was mostly correct for what I needed.  To solve this problem, there is a .json file under /lib called compiledCities.json.  This is what the module reads from.  To create that file, you can run "node compileCountries.js"

This will create compiledCities.json from the data in /src.  Feel free to correct or fill in that data in /src and send a pull request.  Hopefully when these small blanks get filled in, we will have a more complete database.
