### ISSUE TITLE
Empty cities array for states named with multiple words

### ISSUE THREAD

**Issue by ADavidLiu** [khkwan0/countryCityStateJson#4]
I was working with the data from Colombia, but the cities from states with names composed of more than 1 word (Valle del Cauca, Norte de Santander, etc.) are returning an empty array.

**Comment by khkwan0** [comment]
Yes, the data I pulled from had some missing/erroneous information.  I did not personally gather the data.  However, in /lib you can fill in the .json file and run "node compilecountries.js" and it will spit out your updated database which you can use.  

I personally am not maintaining the database itself, I am maintaining the code that compiles and reads from that database.

**Comment by ADavidLiu** [comment]
Thanks for getting back. I'm updating city.json to add the missing cities, but I was wondering if I really have to manually update all the id fields of the next hundreds of cities in the array. Is it necessary for the correct functioning of the package?

**Comment by khkwan0** [comment]
that's strange, it should've created a new file.  you don't have to edit everything, just whatever you think.  if you still happen to have your changes i'd like to incorporate into this repo.

**Comment by ADavidLiu** [comment]
I uploaded the edited `city.json` here: https://gist.github.com/ADavidLiu/2144f2ac457937f57c88e5783d1b0917

The new cities are the ones that have an empty id (`"id": ""`).
