### ISSUE TITLE
City Spelt Wrong

### ISSUE THREAD

**Issue by joshtru** [khkwan0/countryCityStateJson#5]
Looks like one of the city is spelt wrong. It's spelt warMsveld instead of warNsveld.

**Comment by joshtru** [comment]
I corrected the spelling by going into the node node_modules/countrycitystatejson/lib/compiledCities.json. I got a hint from one of your response to one of the issues. This changes are local - only effective in my project and not the global package.

**Comment by khkwan0** [comment]
Ok thanks.
