### ISSUE TITLE
IE11 compatibility issue?

### ISSUE THREAD

**Issue by Lovecannon** [khkwan0/countryCityStateJson#6]
Hello, I use this library with VueJS and webpack and I've noticed that using this library breaks IE11 compatibility on my site. 

IE11 reports a syntax error in this bundled code:

eval("const db = __webpack_require__(/*! ./lib/compiledCities.json */ \"./node_modules/countrycitystatejson/lib/compiledCities.json\")\n\nvar compCities = {\n\n  getAll: () => { return db },\n  getCountriesShort: () => {\n    let res = []\n    for (var key in db) {\n      res.push(key)\n    }\n    return res\n  },\n  getCountryByShort: (shortName) => {\n    if (typeof db[shortName] !== 'undefined') {\n      return db[shortName]\n    } else {\n      return null\n    }\n  },\n  getCountryInfoByShort: (shortName) => {\n    if (typeof db[shortName] !== 'undefined') {\n      let res = {}\n      for (var key in db[shortName]) {\n        if (key !== 'states') {\n          res[key] = db[shortName][key]\n        }\n      }\n      return res\n    } else {\n      return null\n    }\n  },\n  getStatesByShort: (shortName) => {\n    if (typeof db[shortName] !== 'undefined') {\n      let res = []\n      if (typeof db[shortName].states !== 'undefined') {\n        res = Object.keys(db[shortName].states)\n        return res\n      } else {\n        return null\n      }\n    } else {\n      return null\n    }\n  },\n  getCities: (shortName, state) => {\n    if (typeof db[shortName] !== 'undefined') {\n      if (typeof db[shortName].states != 'undefined') {\n        let res=[]\n        for (let idx in  db[shortName].states[state]) {\n          res.push(db[shortName].states[state][idx].name)\n        }\n        return res\n      } else {\n        return null\n      }\n    } else {\n      return null\n    }\n  },\n  getCountries: () => {\n    let res = []\n    for (var shortName in db) {\n      let obj = {}\n      for (var key in db[shortName]) {\n        if (key !== 'states') {\n          obj.shortName = shortName\n          obj[key] = db[shortName][key]\n        }\n      }\n      res.push(obj)\n    }\n    return res\n  }\n}\n\nmodule.exports = compCities\n\n\n//# sourceURL=webpack:///./node_modules/countrycitystatejson/index.js?");

**Comment by khkwan0** [comment]
I will take a look at it

**Comment by khkwan0** [comment]
Interesting.  i've never tried this on a browser. 

i wrote this towards node.js on the backend.  However, it _should_ work on the front end.  It's javascript after all.  

I'll see if I can learn vue really quick and test it.  I'll also test it under react as well.

**Comment by Lovecannon** [comment]
Any progress on this?

**Comment by khkwan0** [comment]
havent had a chance to test it on front end yet.
